### PR TITLE
use unit to assign slot for actions

### LINKED ISSUE #2911: Actions tab doesn't show values
https://www.opendota.com/matches/6456563445/actions

### PR DESCRIPTION
**Pull request by builder-247**
Fixes https://github.com/odota/web/issues/2911

### CODE REVIEW

**Comment by builder-247** [comment]
Needs some more testing, but this should also fix the chat issue

**Comment by howardchung** [comment]
Let me know when you're confident it can be merged

**Comment by builder-247** [comment]
Current implementation breaks for messages sent before picking a hero. Tried reading `CDemoFileInfo` by adding this to the `Parse` class

```java
      CDemoFileInfo info = Clarity.infoForStream(is);
```
but I am getting a 
```
java.io.IOException: given stream does not seem to contain a valid replay
        at skadistats.clarity.source.Source.readEngineType(Source.java:165)
        at skadistats.clarity.processor.runner.SimpleRunner.<init>(SimpleRunner.java:28)
        at opendota.Parse.<init>(Parse.java:202)
        at opendota.Main$MyHandler.handle(Main.java:27)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

```
error. Any ideas?

**Comment by builder-247** [comment]
The current implementation doesn't work for events before picking a hero, however I think it should work as a temporary fix. A better solution is more difficult and I probably won't have time to look into it until the weekend.

**Comment by howardchung** [comment]
Can we make this backward compatiable and keep the existing behavior for older replays?

**Comment by Markxy** [comment]
@builder-247 did the new playerEnt->slot method here not fix #52 ? 
I'm curious of the revert here as my implementation was similar.

**Comment by builder-247** [comment]
> @builder-247 did the new playerEnt->slot method here not fix #52 ? I'm curious of the revert here as my implementation was similar.

I think it works in theory, but the current parser implementation only allows to assign the map at hero pick, so you can't assign players correctly pre-draft. I tried reading the metadata at start but it somehow seemed to invalidate the replay stream or something, need to look into it more - perhaps use the advanced runner.

**Pull request merged**
